### ISSUE TITLE
Where did your boxy-svg-snap repo go?

### ISSUE THREAD

**Issue by Botspot** [boxy-svg/boxy-svg-locales#1]
Just wondering why you removed your boxy-svg-snap repository. This broke updates for our ARM Linux app store.
Is there a new way we should be downloading your electron packages from https://firebasestorage.googleapis.com/v0/b/boxy-svg.appspot.com?

**Comment by jarek-foksa** [comment]
I'm sorry about that, I recently [dropped support for Snap](https://boxy-svg.com/blog/22/snap-linux-app-to-be-deprecated-soon) and Flatpak is currently the only officially supported format.

You could use the [Flatpak YAML file](https://github.com/flathub/com.boxy_svg.BoxySVG/blob/master/com.boxy_svg.BoxySVG.yaml) to generate corresponding Snap configuration file, but I really can't guarantee you there will be no breaking changes in future when I update dependencies and enable Wayland by default. The last time I tried, I was unable to make the latest version of Electron builder compile native node modules for Snap.

BTW, please use email or the official support forum to contact me, I will be [removing this repo](https://boxy-svg.com/ideas/221/localization-and-internationalization#comment-2586) soon.
